### ISSUE TITLE
Specs - should we use TDD already?

### ISSUE THREAD

**Issue by 5v3n** [5v3n/ratpack#3]
The whole project is rather small. The sinatra api is quite compact, question is: should we already start in a TDD manner from the beginning or would it be over-engineering at this state?

Plus: how should we test the Arduino code?

Thoughts welcome (cc @nerdsrob, @jessescott)

**Comment by nerdsRob** [comment]
IMHO TDD should **never** be seen as 'over-engineering' even in smaller projects, since code grows over time eventually and at some point of complexity you will be very thankful when the architecture was driven by and derived from tests from the very beginning. 

I am not sure about Arduino code testing, but maybe [ArduinoUnit](https://github.com/mmurdoch/arduinounit) might be a good starting point? :flashlight:

**Comment by 5v3n** [comment]
I see the argument - although 'eventually' is the reason I didn't introduce specs yet. Plus I worked on the code on my own so far.

I guess what could tip the scale 'pro testing' is that it's published open source - so there's _potentially_ someone else working on it too which could make tests a must have.

If we want to reach a useful coverage the ruby part is simple: I'd use rspec for the api & unti tests. Perhaps even spec the web client, it's not too much work.

The Arduino part is new territory for me. ArduniUnit sounds promising. What would make it even more awesome would be some kind of atmel vm / virtualization. 

If we reach that point, a CI scenario could make sense. This will be when I'll add Atmel-C / Arduino-C to @travis-ci and prepare some Ardunio boards for the  crew to attach them to their setup ;-). /cc @rkh @svenfuchs

Seriously: Agreed, I'll start with some specs for the sinatra part. @nerdsRob did you use ArduinoUnit already?
